import logging
import asyncio
from pyrogram import Client, filters, enums
from pyrogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton
from config import Config
from database import db

# Initialize logging
logging.basicConfig(
    level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        )

        class VJBot(Client):
            def __init__(self):
                    super().__init__(
                                "vj_bot",
                                            api_id=Config.API_ID,
                                                        api_hash=Config.API_HASH,
                                                                    bot_token=Config.BOT_TOKEN,
                                                                                workers=4,
                                                                                            sleep_threshold=30
                                                                                                    )
                                                                                                            self.batch_tasks = {}

                                                                                                                async def start(self):
                                                                                                                        await super().start()
                                                                                                                                logging.info("Bot started successfully")
                                                                                                                                        
                                                                                                                                                # Initialize database
                                                                                                                                                        await db.initialize()

                                                                                                                                                            async def stop(self, *args):
                                                                                                                                                                    await super().stop()
                                                                                                                                                                            logging.info("Bot stopped successfully")

                                                                                                                                                                            # Initialize bot
                                                                                                                                                                            bot = VJBot()

                                                                                                                                                                            # ======================
                                                                                                                                                                            # LOGIN HANDLER
                                                                                                                                                                            # ======================
                                                                                                                                                                            @bot.on_message(filters.command("login") & filters.private)
                                                                                                                                                                            async def handle_login(client: Client, message: Message):
                                                                                                                                                                                try:
                                                                                                                                                                                        # Step 1: Get phone number
                                                                                                                                                                                                await message.reply("📱 Please send your phone number with country code (e.g., +1234567890)")
                                                                                                                                                                                                        phone_number_msg = await client.listen(message.chat.id)
                                                                                                                                                                                                                
                                                                                                                                                                                                                        # Step 2: Send OTP
                                                                                                                                                                                                                                sent_code = await client.send_code(phone_number_msg.text)
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                # Step 3: Get OTP
                                                                                                                                                                                                                                                        await message.reply("🔢 Please send the OTP you received (format: 1 2 3 4 5)")
                                                                                                                                                                                                                                                                otp_msg = await client.listen(message.chat.id)
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                # Step 4: Sign in
                                                                                                                                                                                                                                                                                        await client.sign_in(
                                                                                                                                                                                                                                                                                                    phone_number_msg.text,
                                                                                                                                                                                                                                                                                                                sent_code.phone_code_hash,
                                                                                                                                                                                                                                                                                                                            otp_msg.text.replace(" ", "")
                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                    # Step 5: Save session
                                                                                                                                                                                                                                                                                                                                                            session_string = await client.export_session_string()
                                                                                                                                                                                                                                                                                                                                                                    await db.users.update_session(message.from_user.id, session_string)
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                    await message.reply("✅ Login successful!")

                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                logging.error(f"Login error: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                        await message.reply("❌ Login failed. Please try /login again.")

                                                                                                                                                                                                                                                                                                                                                                                                        # ======================
                                                                                                                                                                                                                                                                                                                                                                                                        # CONTENT HANDLER
                                                                                                                                                                                                                                                                                                                                                                                                        # ======================
                                                                                                                                                                                                                                                                                                                                                                                                        @bot.on_message(filters.text & filters.private)
                                                                                                                                                                                                                                                                                                                                                                                                        async def handle_content(client: Client, message: Message):
                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                    if "t.me/" not in message.text:
                                                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                user_data = await db.users.get_user(message.from_user.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if not user_data or not user_data.get("session"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return await message.reply("🔒 Please /login first to access content")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Process Telegram link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            parts = message.text.split("/")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if len(parts) < 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return await message.reply("❌ Invalid link format")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Implement content downloading logic here
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await message.reply("📥 Processing your request...")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logging.error(f"Content error: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if Config.ERROR_MESSAGE:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await message.reply(f"❌ Error: {str(e)}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bot.run()run()